#Should the Plugin use the PlaceholderAPI for Placeholders
PlaceholderAPI: false
#All Consolen-Messages
Console:
  PrefixConsole: '&7[&eOnJoin&7]'
  newupdatebconrl: 'New version available! You can download the new version at SpigotMC!'
#Messages - Command Onjoin
Help:
  HelpText:
    - ''
    - '&e--------- &7[&aHELP &7| &eOnJoin&7]&e ---------'
    - '&e|  '
    - '&e|  &7/&eonjoin'
    - '&e|    &c->  &7Overview'
    - '&e|  '
    - '&e|  &7/&eonjoin &areloadconfig'
    - '&e|    &c->  &7Reload your config'
    - '&e|  '
    - '&e--------- &7[&aHELP &7| &eOnJoin&7]&e ---------'
    - ''
  OutConfigCreate: 'Config generated in plugins folder!'
  OutConfigLoad: 'All settings from configuration loaded successfully!'
#General Messages
Prefix: '&7[&eOnJoin&7] &7Â»&e '
Permissionfail: "&cYou don't have permission to do this!"
TargetFalse: "&cPlayer is not online or doesn't exist"
NoPlayer: 'Only players can do that!'
#Titel in the middle of the screen
Title:
  TitleOnJoin: true
  Title1: '&bCC&3SW'
  SubTitle1: '&eOnJoin'
  SubTitle2: '&aTitle&8 - &7Edit it in &8onjoin.yml'
#Welcome Message in the Chat
WelcomeMessage:
  WelcomeMessageOn: true
  #You can add and remove as many lines as you like!
  WelcomeMessageText:
    - '&e------------------------------------'
    - '&e|  '
    - '&e|  Heey, &a%player%&7!'
    - '&e|  &eWelcome to our Server!'
    - '&e|  '
    - '&e|  &eOnJoin &8- &7Your Join Plugin'
    - '&e|  &7Plugin by &bTigerpanzer_02/Tigerkatze'
    - '&e|  &7Your Network @CC-SW'
    - '&e|  '
    - '&e------------------------------------'
#Should there be a message to all players when a player enters the server
Join:
  #Should it sends a message to Player with the Permission
  UpdateMessageOn: true
  UpdateMessageText:
    - '&e--------- &7[&aUPDATE &7| &eOnJoin&7]&e ---------'
    - '&c|  New Update is avaible! You can'
    - '&c|  download at SpigotMC!'
    - '&c|  https://www.spigotmc.org/resources/56907/'
    - '&e--------- &7[&aUPDATE &7| &eOnJoin&7]&e ---------'
  #Should the chat be cleaned up by the player at the beginning?
  ChatClearOn: true
  #Should the Player with Permission OnJoin.* or OnJoin.Firework have a Firework when he joins?
  Firework-On: true
  Firework:
    Instant-Explode: false
    Amount: 3
    Firework-Height: 3
    Power: 1
    Type: BALL
    Flicker: false
    Trail: false
    Colors:
    - YELLOW
    Fade:
    - WHITE
  JoinMessageOn: true
  JoinMessage: '&7%player% has joined the Server'
  #Should there be a sound
  JoinSoundOn: true
  JoinSound: FIREWORK_LAUNCH
#Should the Player that join heal
Heal:
  HealOn: true
  Health: 20
  FoodLevel: 20
  ClearPotionEffects: true
#Should the Player that join with Permission heal
  HealOnWithPermission: true
  HealthWithPermission: 20
  FoodLevelWithPermission: 20
  ClearPotionEffectsWithPermission: true
#Execute Commands after Join
ExecuteCommand:
  CommandOn: true
  Commands:
    - 'console;say %player% Hello! Change this in Config!'
    - 'player;help'
#Message on the actionbar
actionbar:
  actionbaronjoin: true
  actionbar1: '&7Welcome %player%!'
  actionbar2: '&7 CC-SW Network'
#Should there be a message to all players when a player leaves the server
Quit:
  QuitMessageOn: true
  QuitMessage: '&7%player% has left the Server'
  #Should there be a sound
  QuitSoundOn: true
  QuitSound: BAT_DEATH
